# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_genuine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='genuine',
            new_name='featured',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
